### ISSUE TITLE
implement POST /user on backend

### ISSUE THREAD

**Issue by meatballhat** [globallinks/volunteer-portal#24]

**Comment by catebest** [comment]
email not found -> 404
username on different email -> 409
email+username exist -> 401
all good -> 201

**Comment by catebest** [comment]
{
  "email" : "...",
  "username" : "...",
  "password" : "..."
}

**Comment by amcoder** [comment]
Try to find a volunteer with the provided email address.
- Email not found -> 404
- Username already in use, but not on the same volunteer -> 409
- One volunteer matches the email
  - No username exists yet - 201 + create
  - Username does not match - 409
  - Username matches
    - Account exists -> 409 (Account already exists)
    - Account does not exist -> 201 + create
- Multiple volunteers matched to that email
  - Username matches neither of them -> 409 (Multiple matches) Email volunteer coordinator.
  - Username matches one of them
    - Account already set up for that volunteer -> 409 (Account already exists)
    - Account does not exist for that  volunteer -> 201 + create

**Comment by amcoder** [comment]
@kpytang,

409 error types:
- ACCOUNT_EXISTS
- WRONG_USERNAME
- MULTIPLE_MATCHES
