### ISSUE TITLE
User not being redirected to /login

### ISSUE THREAD

**Issue by amcoder** [globallinks/volunteer-portal#61]
Reproduce:
- Log out
- Go to <host>/#/checkin

Expected: Redirects user to /#/auth/login

Actual: Check in page is displayed

**Comment by kpytang** [comment]
fixed by https://github.com/globallinks/volunteer-portal/commit/057c3f5a0a42c6ac1f52367bea4df2c1f94ac214.

latest version hadn't been pushed to heroki
